[package]
name = "sunshine-client"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

license = "GPL-3.0"
readme = "README.md"
description = "Submit extrinsics (transactions) to the sunshine node via RPC"
keywords = ["parity", "substrate", "blockchain", "sunshine"]

[features]
light-client = ["substrate-subxt-light-client", "sunshine-node"]

[dependencies]
codec = { version = "1.2", package = "parity-scale-codec", default-features = false, features = ["derive", "full"] }
frame-support = "2.0.0-alpha.6"
pallet-indices = "2.0.0-alpha.6"
substrate-subxt = "0.6.0"
substrate-subxt-light-client = { version = "0.1.0", optional = true }
sunshine-node = { path = "../node", optional = true }
sp-core = "2.0.0-alpha.6"
sp-runtime = "2.0.0-alpha.6"
thiserror = "1.0.15"
util = { path = "../modules/util", default-features = false }

[dev-dependencies]
async-std = { version = "1.5.0", features = ["attributes"] }
env_logger = "0.7.1"
sp-keyring = "2.0.0-alpha.6"
