[profile.release]
panic = "unwind"

[workspace]
members = [
    "bin/bot",
    "bin/cli",
    "bin/client",
    "bin/runtime",
    "bin/node",
    "client/cli",
    "client/client",
    "client/ffi",
    "client/gbot",
    "pallets/bank",
    "pallets/bounty",
    "pallets/court",
    "pallets/donate",
    "pallets/drip",
    "pallets/grant",
    "pallets/org",
    "pallets/treasury",
    "pallets/vote",
    "utils",
]

[patch.crates-io]
sunshine-identity-cli = { git = "https://github.com/sunshine-protocol/sunshine-identity" }
substrate-keybase-keystore = { git = "https://github.com/sunshine-protocol/sunshine-identity" }
sunshine-core = { git = "https://github.com/sunshine-protocol/sunshine-identity" }
