[profile.release]
panic = "unwind"

[workspace]
members = [
    "bin/cli",
    "bin/client",
    "bin/runtime",
    "bin/node",
    "client/cli",
    "client/client",
    "client/ffi",
    "client/gbot",
    "pallets/bank",
    "pallets/bounty",
    "pallets/bounty2",
    "pallets/court",
    "pallets/donate",
    "pallets/drip",
    "pallets/grant",
    "pallets/kickback",
    "pallets/moloch",
    "pallets/org",
    "pallets/treasury",
    "pallets/vote",
    "pallets/vote-direct",
    "utils",
]

[patch.crates-io]
substrate-subxt = { git = "https://github.com/paritytech/substrate-subxt/" }
