[profile.release]
panic = "unwind"

[workspace]
members = [
    "bin/node",
    "bin/cli",
    "pallets-util",
    "pallets/org",
    "pallets/vote",
    "pallets/bank",
    "pallets/bounty",
    "client",
]
