[profile.release]
panic = "unwind"

[workspace]
members = [
    "bin/bot",
    "bin/cli",
    "bin/client",
    "bin/runtime",
    "bin/node",
    "client/cli",
    "client/client",
    "client/gbot",
    "pallets/bank",
    "pallets/bounty",
    "pallets/bounty2",
    "pallets/court",
    "pallets/donate",
    "pallets/drip",
    "pallets/org",
    "pallets/treasury",
    "pallets/vote",
    "utils",
]

[patch.crates-io]
substrate-subxt = { git = "https://github.com/paritytech/substrate-subxt" }
sunshine-identity-cli = { git = "https://github.com/sunshine-protocol/sunshine-identity" }
keybase-keystore = { git = "https://github.com/sunshine-protocol/sunshine-identity" }