[profile.release]
panic = "unwind"

[workspace]
members = [
    "bin/cli",
    "bin/client",
    "bin/runtime",
    "bin/bot",
    "bin/node",
    "client/cli",
    "client/client",
    "pallets/bank",
    "pallets/bounty",
    "pallets/court",
    "pallets/donate",
    "pallets/org",
    "pallets/treasury",
    "pallets/vote",
    "utils",
]
