[profile.release]
panic = "unwind"

[workspace]
members = [
    "bin/runtime",
    "bin/node",
    "bin/cli",
    "client/client",
    "client/cli",
    "pallets-util",
    "pallets/org",
    "pallets/vote",
    "pallets/court",
    "pallets/bank",
    "pallets/donate",
    "pallets/bounty",
]
