[package]
name = "suntime"
version = "0.0.1"
authors = ["4meta5"]
edition = "2018"

[dependencies]
serde = { version = "1.0.101", optional = true, features = ["derive"] }
codec = { package = "parity-scale-codec", version = "1.1.2", default-features = false, features = ["derive"] }
sp-std = { git = "https://github.com/paritytech/substrate.git", default-features = false }
sp-io = { git = "https://github.com/paritytech/substrate.git", default-features = false }
sp-version = { git = "https://github.com/paritytech/substrate.git", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate.git", default-features = false }
sp-session = { git = "https://github.com/paritytech/substrate.git", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", default-features = false }
sp-offchain = { git = "https://github.com/paritytech/substrate.git", default-features = false }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate.git", default-features = false }
sp-block-builder = { git = "https://github.com/paritytech/substrate.git", default-features = false }
sp-api = { git = "https://github.com/paritytech/substrate.git", default-features = false }
sp-inherents = { git = "https://github.com/paritytech/substrate.git", default-features = false }
sp-staking = { git = "https://github.com/paritytech/substrate.git", default-features = false }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate.git", default-features = false }

system = { package = "frame-system", git = "https://github.com/paritytech/substrate.git", default-features = false }
frame-support = { git = "https://github.com/paritytech/substrate.git", default-features = false }
frame-executive = { git = "https://github.com/paritytech/substrate.git", default-features = false }
system-rpc-runtime-api = { package = "frame-system-rpc-runtime-api", git = "https://github.com/paritytech/substrate", default-features = false }
pallet-balances = { git = "https://github.com/paritytech/substrate.git", default-features = false }
pallet-grandpa = { git = "https://github.com/paritytech/substrate.git", default-features = false }
pallet-indices = { git = "https://github.com/paritytech/substrate.git", default-features = false }
pallet-randomness-collective-flip = { git = "https://github.com/paritytech/substrate.git", default-features = false }
pallet-timestamp = { git = "https://github.com/paritytech/substrate.git", default-features = false }
pallet-sudo = { git = "https://github.com/paritytech/substrate.git", default-features = false }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate.git", default-features = false }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", default-features = false }
pallet-collective = { git = "https://github.com/paritytech/substrate.git", default-features = false }
pallet-membership = { git = "https://github.com/paritytech/substrate.git", default-features = false }
pallet-treasury = { git = "https://github.com/paritytech/substrate.git", default-features = false }
pallet-staking = { git = "https://github.com/paritytech/substrate.git", default-features = false }
pallet-staking-reward-curve = { git = "https://github.com/paritytech/substrate.git", default-features = false }
pallet-session = { git = "https://github.com/paritytech/substrate.git", default-features = false }
pallet-babe = { git = "https://github.com/paritytech/substrate.git", default-features = false }
permissioned-share-collective = { path = "../srml/permissioned-share-collective", package = "permissioned-share-collective", default-features = false }
clear_on_drop = { version = "0.2.3", features = ["no_cc"] }	# https://github.com/paritytech/substrate/issues/4179

[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "1.0.4" }

[features]
default = ["std"]
no_std = []
std = [
	"codec/std",
	"sp-std/std",
	"sp-io/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-version/std",
	"serde",
	"sp-offchain/std",
	"sp-session/std",
	"sp-transaction-pool/std",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-inherents/std",
	"sp-consensus-babe/std",
	"system/std",
	"frame-support/std",
	"frame-executive/std",
	"pallet-balances/std",
	"pallet-babe/std",
	"pallet-grandpa/std",
	"pallet-indices/std",
	"pallet-collective/std",
	"pallet-membership/std",
	"pallet-timestamp/std",
	"pallet-sudo/std",
	"pallet-transaction-payment/std",
	"pallet-randomness-collective-flip/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-treasury/std",
	"pallet-staking/std",
	"system-rpc-runtime-api/std",
    "permissioned-share-collective/std",
]