[package]
name = "sunshine-github-bot"
version = "0.0.1"
authors = ["Amar Singh <asinghchrony@protonmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2.17", default-features = false, features = ["macros"] }
octocrab = "0.4.2"
substrate-subxt = { version = "0.10.1", features = ["client"] }
sunshine-bounty-client = { path = "../client" }
thiserror = "1.0.20"
