[package]
name = "sunshine-bounty-gbot"
version = "0.0.1"
authors = ["Amar Singh <asinghchrony@protonmail.com>"]
edition = "2018"
description = "github bot for sunshine bounty"

[dependencies]
chrono = { version = "0.4.11", features = ["serde"] }
octocrab = "0.5.0"
thiserror = "1.0.20"

[dev-dependencies]
tokio = { version = "0.2.22", default-features = false, features = ["macros"] }
env_logger = "0.7.1"
