[package]
name = "test-client"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>, Amar Singh <asingchrony@protonmail.com>"]
edition = "2018"

[features]
mock = [
    "sunshine-client-utils/mock",
]

[dependencies]
async-trait = "0.1.40"
libipld = { version = "0.6.1", default-features = false }
substrate-subxt = "0.12.0"
sunshine-bounty-client = { path = "../../client/client" }
sunshine-bounty-utils =  { path = "../../utils" }
sunshine-codec = { default-features=false, git = "https://github.com/sunshine-protocol/sunshine-core" }
tiny-cid = { version = "0.2.8", features = ["serde-codec"] }
sunshine-client-utils = { git = "https://github.com/sunshine-protocol/sunshine-core" }
test-node = { path = "../node" }

# workaround subxt event decoding
sunshine-faucet-client = { git = "https://github.com/sunshine-protocol/sunshine-identity" }
sunshine-identity-client = { git = "https://github.com/sunshine-protocol/sunshine-identity" }
