[package]
name = "test-client"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>, Amar Singh <asingchrony@protonmail.com>"]
edition = "2018"

[features]
mock = [
    "env_logger",
    "jsonrpsee",
    "sp-keyring",
    "tempdir",
    "test-node",
]

[dependencies]
async-trait = "0.1.36"
bounty-client = { package = "sunshine-bounty-client", path = "../../client/client" }
bounty-utils =  { package = "sunshine-bounty-utils", path = "../../utils" }
codec = { version = "1.3.1", package = "parity-scale-codec" }
identity-utils = { package = "sunshine-identity-utils", version = "0.2.0" }
ipfs-embed = "0.3.0"
ipld-block-builder = "0.4.1"
libipld = { version = "0.3.0", default-features = false }
sled = "0.32.1"
substrate-subxt = { version = "0.10.1", features = ["client"] }
substrate-keybase-keystore = "0.2.0"
sunshine-core = "0.2.0"
thiserror = "1.0.20"

env_logger = { version = "0.7.1", optional = true }
jsonrpsee = { version = "0.1.0", optional = true }
sp-keyring = { version = "2.0.0-rc5", optional = true }
tempdir = { version = "0.3.7", optional = true }
test-node = { path = "../node", optional = true }
