[package]
authors = ['4meta5']
edition = '2018'
homepage = 'https://sunshine.foundation'
license = 'GPL-3.0'
name = 'test-runtime'
repository = 'https://github.com/sunshine-protocol/sunshine-bounty/'
version = '0.0.1'

[features]
default = ['std']
std = [
    'parity-scale-codec/std',
    'frame-executive/std',
    'frame-support/std',
    'frame-system/std',
    'pallet-aura/std',
    'pallet-balances/std',
    'pallet-grandpa/std',
    'pallet-randomness-collective-flip/std',
    'pallet-timestamp/std',
    'pallet-transaction-payment/std',
    'serde',
    'sp-api/std',
    'sp-block-builder/std',
    'sp-consensus-aura/std',
    'sp-core/std',
    'sp-inherents/std',
    'sp-io/std',
    'sp-offchain/std',
    'sp-runtime/std',
    'sp-session/std',
    'sp-std/std',
    'sp-transaction-pool/std',
    'sp-version/std',
    'util/std',
    'org/std',
    'treasury/std',
    'grant/std',
]

[build-dependencies]
wasm-builder-runner = { version = "1.0.6", package = "substrate-wasm-builder-runner" }

[dependencies]
serde = { version = "1.0.115", features = ["derive"], optional = true }
parity-scale-codec = { version = "1.3.4", default-features = false, features = ["derive"] }
frame-executive = { version = "2.0.0-rc6", default-features = false }
frame-support = { version = "2.0.0-rc6", default-features = false }
frame-system = { version = "2.0.0-rc6", default-features = false }
pallet-aura = { version = "2.0.0-rc6", default-features = false }
pallet-balances = { version = "2.0.0-rc6", default-features = false }
pallet-grandpa = { version = "2.0.0-rc6", default-features = false }
pallet-randomness-collective-flip = { version = "2.0.0-rc6", default-features = false }
pallet-timestamp = { version = "2.0.0-rc6", default-features = false }
pallet-transaction-payment = { version = "2.0.0-rc6", default-features = false }
sp-api = { version = "2.0.0-rc6", default-features = false }
sp-block-builder = { version = "2.0.0-rc6", default-features = false }
sp-consensus-aura = { version = "0.8.0-rc6", default-features = false }
sp-core = { version = "2.0.0-rc6", default-features = false }
sp-inherents = { version = "2.0.0-rc6", default-features = false }
sp-io = { version = "2.0.0-rc6", default-features = false }
sp-offchain = { version = "2.0.0-rc6", default-features = false }
sp-runtime = { version = "2.0.0-rc6", default-features = false }
sp-session = { version = "2.0.0-rc6", default-features = false }
sp-std = { version = "2.0.0-rc6", default-features = false }
sp-transaction-pool = { version = "2.0.0-rc6", default-features = false }
sp-version = { version = "2.0.0-rc6", default-features = false }

util = { package = "sunshine-bounty-utils", path = "../../utils", default-features=false}
org = {package = "sunshine-org", path = "../../pallets/org", default-features=false }
vote = { package = "sunshine-vote", path = "../../pallets/vote", default-features=false}
drip = { package = "sunshine-drip", path = "../../pallets/drip", default-features=false}
treasury = { package = "sunshine-treasury", path = "../../pallets/treasury", default-features=false}
donate = { package = "sunshine-donate", path = "../../pallets/donate", default-features=false}
bank = { package = "sunshine-bank", path = "../../pallets/bank", default-features=false}
bounty = { package = "sunshine-bounty", path = "../../pallets/bounty", default-features=false}
grant = { package = "sunshine-grant", path = "../../pallets/grant", default-features=false}
