[package]
name = "sunshine-bors"
version = "0.0.1"
authors = ["Amar Singh <asinghchrony@protonmail.com>"]
edition = "2018"

[dependencies]
dirs = "3.0.1"
env_logger = "0.7.1"
gbot = { package = "sunshine-bounty-gbot", path = "../../client/gbot" }
ipfs-embed = "0.3.0"
ipld-block-builder = "0.4.1"
libipld = "0.3.0"
substrate-subxt = { version = "0.10.1", features = ["client"] }
sunshine_bounty_client = { package = "sunshine-bounty-client", path = "../../client/client" }
sunshine-core = "0.2.0"
test-client = { path = "../client" }
thiserror = "1.0.20"
tokio = { version = "0.2.17", default-features = false, features = ["macros"] }