[package]
name = "bounty-cli"
version = "0.2.0"
authors = ["David Craven <david@craven.ch>, Amar Singh <asinghchrony@protonmail.com>"]
edition = "2018"

[dependencies]
async-std = { version = "1.6.2", features = ["attributes"] }
clap = "3.0.0-beta.1"
dirs = "3.0.1"
env_logger = "0.7.1"
sunshine-bounty-cli = { path = "../../client/cli" }
sunshine-cli-utils = { git = "https://github.com/sunshine-protocol/sunshine-core" }
test-client = { path = "../client" }
